services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:9090:9090"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_SESSIONSFOLDER=/app/spotifySessions
    volumes:
      - ./uploads:/app/spotifySessions
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:8080:80"